#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time
import colors as c

GPIO.setmode(GPIO.BCM)
pins = [17,27,22,5,6,13,19,26]
set_num = 0
num = 0
set_num2 = 0
off_num = 0
GPIO.setwarnings(False)
for item in pins:
   GPIO.setup(pins[set_num], GPIO.OUT)
   set_num += 1
GPIO.setup(24, GPIO.IN)

try:
   while True:
      inputValue = GPIO.input(24)
      if inputValue == True or num == 254:
         speed = input("What Speed?\n")
         for item2 in pins:
            GPIO.output(pins[set_num2], 0)
            set_num2 += 1
         for num in range(255):
            current_binary = 0
            current_pin = 0
            binary = list(bin(num)[:1:-1])
            for z in pins:
               GPIO.output(pins[off_num], 0)
               set_num += 1
            if num < 2:
               repeat_times = 1
            elif num > 1 and num < 4:
               repeat_times = 2
            elif num > 3 and num < 8:
               repeat_times = 3
            elif num > 7 and num < 16:
               repeat_times = 4
            elif num > 15 and num < 32:
               repeat_times = 5
            elif num > 31 and num < 64:
               repeat_times = 6
            elif num > 63 and num < 128:
               repeat_times = 7
            elif num < 127:
               repeat_times = 8
            print(c.clear)
            inputValue = GPIO.input(24)
            if inputValue == True:
               print(c.blue + "Let Go!" + c.reset)
               time.sleep(1.5)
               break
            for o in range(repeat_times):
               GPIO.output(pins[current_pin], int(binary[current_binary]))
               current_binary += 1
               current_pin += 1
            print("Number:" + str(num))
            print(binary)
            time.sleep(float(speed))
except KeyboardInterrupt:
   GPIO.cleanup()
   exit()   
