#!/usr/bin/env python3
import time as t
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setup(21, GPIO.OUT)
p1 = GPIO.PWM(21, 10)

p1.start(0)
while True:
   t.sleep(0.5)
   p1.ChangeDutyCycle(10)
   GPIO.output(21, 1)
   t.sleep(0.5)
   GPIO.output(21, 0)
