#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time 

pins = [4,17,27,22,5,22,27,17]
GPIO.setmode(GPIO.BCM)
GPIO.setup(pins, GPIO.OUT)
while True:
   for pin in pins:
      GPIO.output(pin, 1)
      time.sleep(0.08)
      GPIO.output(pin, 0)
