#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

pins = [13,19,26]

GPIO.setmode(GPIO.BCM)

for pin in pins:
   GPIO.setup(pin, GPIO.OUT)
   GPIO.output(pin, 0)

GPIO.output(13, 1)
time.sleep(2)
GPIO.output(13, 0)
GPIO.output(19, 1)
time.sleep(2)
GPIO.output(19, 0)
GPIO.output(26, 1)
time.sleep(2)
GPIO.output(19, 1)
GPIO.output(13, 1)
time.sleep(2)
GPIO.cleanup()
