#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(16, GPIO.IN)
GPIO.setup(21, GPIO.OUT)


while True:
    value = GPIO.input(16)
    print("Senser Value is:" + str(value))
    time.sleep(1)
