#!/usr/bin/env python3
import RPi.GPIO as GPIO
import color_tools as ct
import random as r
import colors as c
import time
import pygame.mixer

pygame.mixer.init(48000, -16, 1, 1024)
sound = pygame.mixer.Sound("beep-02.wav")
music = pygame.mixer.Sound("SuperSmashMouthBros-Final.wav")
channelA = pygame.mixer.Channel(1)
channelB = pygame.mixer.Channel(2)
GPIO.setmode(GPIO.BCM)
out_pins = [20,5,27,17,13,19,26]
in_pins = [21,16,25,22]
ct.all_out(out_pins)
for pin in in_pins:
    GPIO.setup(pin, GPIO.IN)
colors = ['r','b','g','y']
ct.all_off(out_pins)
try:
    while True:
        color = []
        game = 1
        for count in range(4):
            current_color = r.choice(colors)
            color.append(current_color)
        input("Ready?")
        print(c.clear)
        while game == 1:
            your_color = []
            for the_color in color:
                if the_color == 'r':
                    GPIO.output(17, 1)
                    time.sleep(1)
                    GPIO.output(17, 0)
                    time.sleep(1)
                elif the_color == 'b':
                    GPIO.output(27, 1)
                    time.sleep(1)
                    GPIO.output(27, 0)
                    time.sleep(1)
                elif the_color == 'g':
                    GPIO.output(5, 1)
                    time.sleep(1)
                    GPIO.output(5, 0)
                    time.sleep(1)
                elif the_color == 'y':
                    GPIO.output(20, 1)
                    time.sleep(1)
                    GPIO.output(20, 0)
                    time.sleep(1)
                else:
                    print("WARNING")
            for h in color:
                doing = 1
                while doing == 1:
                    if GPIO.input(22) == True:
                        your_color.append('r')
                        print(c.red + "RED" + c.reset)
                        channelA.play(sound)
                        doing = 0
                        time.sleep(1)
                    elif GPIO.input(25) == True:
                        your_color.append('b')
                        print(c.blue + "BLUE" + c.reset)
                        channelA.play(sound)
                        doing = 0
                        time.sleep(1)
                    elif GPIO.input(16) == True:
                        your_color.append('g')
                        print(c.green + "GREEN" + c.reset)
                        channelA.play(sound)
                        doing = 0
                        time.sleep(1)
                    elif GPIO.input(21) == True:
                        your_color.append('y')
                        print(c.yellow + "YELLOW" + c.reset)
                        channelA.play(sound)
                        doing = 0
                        time.sleep(1)

            if color == your_color:
                print(c.green + "Correct" + c.reset)
                time.sleep(1)
                print(c.clear)
            else:
                print(c.red + "Wrong" + c.reset)
                time.sleep(1)
                game = 0
                print(c.clear)
            current_color = r.choice(colors)
            color.append(current_color)
except KeyboardInterrupt:
    GPIO.cleanup()
    exit()      
